subroutine ConstructGrid(grid,gridoptions)
    
    ! Description
    !============
    ! This function reads in the grid data (typically from a file 
    ! generated by the grid generator) and saves the necessary
    ! data to the grid. Depending on the 'gridtype' field in the 
    ! 'options' structure, different grid types can be read in - see 
    ! the documentation in the gdmod_userinput module under 
    ! the SetRunFileOptions subroutine, or see the code below.  

    ! Initialize
    !===========
    ! Declare modules
    use goatmod_types
    use goatmod_userinput

    ! The usual
    implicit none

    ! Declare variables
    type(GridUDT)           :: grid
    type(GridOptionsUDT)    :: gridoptions

    integer                 :: filespecifier(0:2)
    
    ! Declare data
    data filespecifier /50, 51, 52/ ! numbers for file specification

    ! Declare external functions
    ! external cfopen

    ! Construct grid
    !===============
    select case (gridoptions%gridtype)

    case ('plasma')

        ! Default plasma edge grid, check the provided format
        select case (gridoptions%inputtype)

        case ('b2fgmtry')

            ! Unstructured format in the b2fgmtry style. 
            ! Open the file containing the grid data
            call cfopen(filespecifier(0), gridoptions%filepath, 'old','un*formatted')

            ! Read in the grid data
            call ReadB2fgmtryUS(filespecifier(0),grid)

            ! Close the file
            close(filespecifier(0))

            ! Extract the grid data structures
            call ExtractGridData(grid, 'b2fgmtry', gridoptions)

        case ('traduitb2us')

            ! Unstructured format in the traduit style.
            ! Open the file containing the grid data
            print *, gridoptions%filepath
            call cfopen(filespecifier(0), gridoptions%filepath, 'old','un*formatted')

            ! Read in the grid data
            call ReadTraduitUS(filespecifier(0),grid)

            ! Close the file
            close(filespecifier(0))

            ! Extract the grid data structures - can use the same 
            ! extraction method as b2fgmtry
            call ExtractGridData(grid, 'traduit', gridoptions)

        case default 

            call gdErrorHandler('unknown plasma grid input type')

        end select


    case default

        call gdErrorHandler('unknown grid type')

    end select

    ! Compute grid interconnections
    !==============================
    call ComputeGridInterconnections(grid)


end subroutine