subroutine ConstructGrid(grid,gridoptions,options)
    
    ! Description
    !============
    ! This function reads in the grid data (typically from a file 
    ! generated by the grid generator) and saves the necessary
    ! data to the grid. Depending on the 'gridtype' field in the 
    ! 'options' structure, different grid types can be read in - see 
    ! the documentation in the gdmod_userinput module under 
    ! the SetRunFileOptions subroutine, or see the code below.  

    ! Initialize
    !===========
    ! Declare modules
    use gdmod_types
    use gdmod_userinput

    ! The usual
    implicit none

    ! Declare variables
    type(GridUDT)           :: grid
    type(GridOptionsUDT)    :: gridoptions
    type(RunfileOptionsUDT) :: options

    integer                 :: filespecifier(0:2)
    
    ! Declare data
    data filespecifier /50, 51, 52/ ! numbers for file specification

    ! Declare external functions
    ! external cfopen

    ! Construct grid
    !===============
    select case(options%gridtype)

    case('plasma')

        ! Default plasma edge grid, check the provided format
        select case(gridoptions%inputtype)

        case('b2fgmtry')

            ! Unstructured format in the b2fgmtry style. 
            ! Open the file containing the grid data
            call cfopen(filespecifier(0),'inputfiles/b2fgmtry_us_tcv','old','un*formatted')

            ! Read in the grid data
            call ReadB2fgmtryUS(filespecifier(0),grid)

            ! Extract the grid data structures
            call ExtractGridData(grid,'b2fgmtry')

        case default 

            call gdErrorHandler('unknown plasma grid input type')

        end select


    case default

        call gdErrorHandler('unknown grid type')

    end select

    ! Compute grid interconnections
    !==============================
    call ComputeGridInterconnections(grid)


end subroutine